import {dataset,loadJSON,uniqueIndex,sitc2Lookup,join,guarded} from './data.js';
import {formatUSD as usd,formatPercent as pct,formatRCA as rca,formatECI as eci,formatPPChange as pp,escapeHTML as esc} from './formatters.js';
import {years,value,checked,on,search} from './filters.js';
import {plot,line,colors,rcaLine} from './charts.js';
import {methodology} from './methodology.js';
const $=id=>document.getElementById(id);let publication,concentration,ecidata;
const detail=(id,title,fields)=>{$(id).innerHTML=`<h3>${esc(title)}</h3><dl>${fields.map(([k,v])=>`<div><dt>${esc(k)}</dt><dd>${esc(v)}</dd></div>`).join('')}</dl>`;};
const kpiExplanations={"cr5_pct": "The combined share of manufactured exports accounted for by the five largest detailed export products in each year.", "eci": "The Economic Complexity Index summarizes how diverse a country’s exports are and how widely those products are exported by other countries. Higher values indicate a more complex export basket."};
const tasks=new Map();function once(name,fn){if(!tasks.has(name))tasks.set(name,fn());return tasks.get(name);}
async function overview(){const [o,c,w,e]=await Promise.all(['export_orientation','export_concentration','world_market_share','eci'].map(dataset));const h=join(join(join(o,uniqueIndex(c,'year'),'year'),uniqueIndex(w,'year'),'year'),uniqueIndex(e,'year'),'year');concentration=c;ecidata=e;const a=h.find(r=>r.year===2000),b=h.find(r=>r.year===2024);const cards=[['Manufactured exports','Constant 2024 USD','manufactured_exports_constant_2024_usd',usd,'usd'],['Manufacturing share of exports','Of all goods exports','manufactured_export_share_pct',pct,'pp'],['Share from top 5 products','Of manufactured exports (CR5)','cr5_pct',pct,'pp'],['Share of global manufactured exports','Pakistan’s global share','pakistan_world_manufacturing_export_share_pct',v=>pct(v,3),'pp3'],['Economic Complexity Index','Export-basket complexity','eci',eci,'index']];$('kpis').innerHTML=cards.map(([title,unit,k,fmt,kind])=>{const delta=b[k]-a[k],change=kind==='usd'?usd(delta):kind==='pp3'?`${delta>0?'+':''}${delta.toFixed(3)} pp`:kind==='pp'?pp(delta):`${delta>0?'+':''}${eci(delta)} index points`;return `<article class="kpi"><h3>${title}</h3><div class="small">2000 → 2024 · ${unit}</div><div class="values">${fmt(a[k])}<span class="arrow">→</span>${fmt(b[k])}</div><div class="change">Change: ${change}</div>${kpiExplanations[k]?`<details class="explanation kpi-help"><summary>What does this mean?</summary><p>${esc(kpiExplanations[k])}</p></details>`:''}</article>`;}).join('');
await Promise.all([plot('orientation-value',[line(o,'manufactured_exports_constant_2024_usd','Manufactured exports',colors[0],r=>`${r.year}<br>${usd(r.manufactured_exports_constant_2024_usd)} · constant 2024 USD`)],{yaxis:{title:{text:'Constant 2024 USD'},tickformat:'.2s',gridcolor:'#E6E6E6'}}),plot('orientation-share',[line(o,'manufactured_export_share_pct','Manufacturing share of total exports',colors[2],r=>`${r.year}<br>${pct(r.manufactured_export_share_pct)}`)],{yaxis:{title:{text:'Share (%)'},gridcolor:'#E6E6E6'}}),concentrationChart(),plot('world-chart',[line(w,'pakistan_world_manufacturing_export_share_pct','Share of global manufactured exports',colors[0],r=>`${r.year}<br>Share of global manufactured exports: ${pct(r.pakistan_world_manufacturing_export_share_pct,3)}<br>Index (2000=100): ${r.pakistan_world_manufacturing_share_index_2000_100.toFixed(2)}`)],{yaxis:{title:{text:'Global share (%)'},tickformat:'.3f',gridcolor:'#E6E6E6'}}),eciChart()]);}
async function concentrationChart(){const m=value('concentration-metric'),level=value('concentration-level');$('aggregation-control').hidden=m!=='hhi';let fields=m==='hhi'?(level==='compare'?['hhi_sitc4','hhi_sitc3']:['hhi_sitc'+level]):m==='both'?['cr5_pct','cr10_pct']:[m+'_pct'];await plot('concentration-chart',fields.map((k,i)=>line(concentration,k,({hhi_sitc4:'Detailed products (SITC4)',hhi_sitc3:'Broader product groups (SITC3)',cr5_pct:'Top 5 products (CR5)',cr10_pct:'Top 10 products (CR10)'})[k],i===0?colors[0]:m==='hhi'?colors[2]:'#7EA6C9')),{yaxis:{title:{text:m==='hhi'?'Concentration index (0–1)':'Share (%)'},gridcolor:'#E6E6E6'}});}
async function eciChart(){await plot('eci-chart',[line(ecidata,'eci','ECI',colors[1],r=>`${r.year}<br>ECI: ${eci(r.eci)}<br>Official rank: ${r.eci_rank}`)],{yaxis:{title:{text:'Complexity index points'},gridcolor:'#E6E6E6'},annotations:checked('eci-ranks')?ecidata.filter(r=>[2000,2010,2024].includes(r.year)).map(r=>({x:r.year,y:r.eci,text:'Rank '+r.eci_rank,showarrow:true,ay:-35,ax:0})):[]});}
async function structure(){const [g,s,l]=await Promise.all(['composition_display_groups','sitc2_composition','sitc2'].map(dataset)),lookup=sitc2Lookup(l);async function render(){const groups=value('composition-view')==='groups',a=+value('composition-a'),b=+value('composition-b');let rows=groups?g:s.map(r=>({...r,display_group:r.sitc2+' · '+lookup.get(r.sitc2).sitc2_name,export_share_pct:r.sitc2_manufacturing_export_share_pct,display_order:+r.sitc2}));let cats=[...new Map(rows.map(r=>[r.display_group,r])).values()].sort((x,y)=>x.display_order-y.display_order);const stable=new Map(cats.map((r,i)=>[r.display_group,colors[i%colors.length]]));if(value('composition-sort')==='share')cats.sort((x,y)=>rows.find(r=>r.year===b&&r.display_group===y.display_group).export_share_pct-rows.find(r=>r.year===b&&r.display_group===x.display_group).export_share_pct);const find=(cat,y)=>rows.find(r=>r.year===y&&r.display_group===cat)?.export_share_pct;function show(cat){$('composition-category').value=cat;detail('composition-detail',cat,[[String(a),pct(find(cat,a),3)],[String(b),pct(find(cat,b),3)],['Change',pp(find(cat,b)-find(cat,a))],['Classification',groups?'Grouped for display':'Broad product group (SITC2) '+cat.slice(0,2)]]);}$('composition-category').innerHTML=cats.map(r=>`<option>${esc(r.display_group)}</option>`).join('');$('composition-category').onchange=()=>show(value('composition-category'));await plot('composition-chart',cats.map(r=>({type:'bar',name:r.display_group,x:[String(a)+' (A)',String(b)+' (B)'],y:[find(r.display_group,a),find(r.display_group,b)],marker:{color:stable.get(r.display_group)},hovertemplate:esc(r.display_group)+'<br>%{x}<br>Share: %{y:.3f}%<extra></extra>'})),{barmode:'stack',height:groups?430:650,yaxis:{title:{text:'Manufactured exports (%)'},range:[0,100],gridcolor:'#E6E6E6'},legend:{orientation:'h',y:-.2,font:{size:11}}},p=>show(p.data.name));show(cats[0].display_group);}on(['composition-view','composition-a','composition-b','composition-sort'],render);await render();}

async function industry(){const [r,l]=await Promise.all(['rca_sitc2_periods','sitc2'].map(dataset));const rows=join(r,sitc2Lookup(l),'sitc2');async function render(){const list=[...rows].sort((a,b)=>b.late_manufacturing_export_share_mean_pct-a.late_manufacturing_export_share_mean_pct).slice(0,value('industry-limit')==='all'?rows.length:10);const label=r=>r.sitc2+' · '+r.sitc2_name;await plot('industry-chart',[['early_rca_mean','RCA, 2000–02','#9FBAD0'],['late_rca_mean','RCA, 2022–24',colors[0]]].map(([k,name,color])=>({type:'bar',orientation:'h',name,x:list.map(r=>r[k]),y:list.map(label),marker:{color},textposition:'none',text:list.map(r=>`${esc(label(r))}<br>RCA, 2000–02: ${rca(r.early_rca_mean)}<br>RCA, 2022–24: ${rca(r.late_rca_mean)}<br>Share of manufactured exports, 2022–24: ${pct(r.late_manufacturing_export_share_mean_pct)}`),hovertemplate:'%{text}<extra></extra>'})),{height:Math.max(480,list.length*35),barmode:'group',margin:{l:window.innerWidth<600?110:260,r:25,t:25,b:80},yaxis:{autorange:'reversed',tickmode:'array',tickvals:list.map(label),ticktext:list.map(r=>window.innerWidth<600?r.sitc2:label(r).slice(0,40)),automargin:true},xaxis:{title:{text:'RCA'},gridcolor:'#E6E6E6'},shapes:[rcaLine],annotations:[{x:1,y:1,xref:'x',yref:'paper',text:'RCA = 1',showarrow:false,yshift:15}]});}on(['industry-limit'],render);await render();}


async function globalDivisions(){const [w,c,r,l]=await Promise.all(['sitc2_world_market_share','sitc2_composition','rca_sitc2','sitc2'].map(dataset)),key=r=>r.year+'|'+r.sitc2;const rows=join(join(join(w,uniqueIndex(c,key),key),uniqueIndex(r,key),key),sitc2Lookup(l),'sitc2');async function render(){const list=rows.filter(r=>r.year===+value('world-year')).sort((a,b)=>b[value('world-sort')]-a[value('world-sort')]).slice(0,value('world-limit')==='all'?34:10),label=r=>r.sitc2+' · '+r.sitc2_name;await plot('division-chart',[{type:'bar',orientation:'h',x:list.map(r=>r.pakistan_world_market_share_pct),y:list.map(label),marker:{color:colors[0]},textposition:'none',text:list.map(r=>`${esc(label(r))}<br>Pakistan share of global exports in this product group: ${pct(r.pakistan_world_market_share_pct,3)}<br>Share of Pakistan’s manufactured exports: ${pct(r.sitc2_manufacturing_export_share_pct,3)}<br>RCA: ${rca(r.rca_sitc2)}`),hovertemplate:'%{text}<extra></extra>'}],{height:Math.max(420,list.length*27),margin:{l:window.innerWidth<600?90:270,r:25,t:25,b:65},xaxis:{title:{text:'Pakistan share of global exports (%)'},gridcolor:'#E6E6E6'},yaxis:{autorange:'reversed',tickmode:'array',tickvals:list.map(label),ticktext:list.map(r=>window.innerWidth<600?r.sitc2:label(r).slice(0,42)),automargin:true}});}on(['world-year','world-limit','world-sort'],render);await render();}

async function start(){
const config=await loadJSON('data/dashboard_config.json');if(config.publication_mode!=='public')throw Error('Invalid presentation mode');const f=config.features;years();
for(const [key,id] of [['research_note_url','research-link'],['repository_url','repository-link']])if(config[key]){$(id).href=config[key];$(id).hidden=false;}
for(const [flag,id] of [['overview','overview'],['export_structure','structure'],['diversification','diversification'],['industry_rca','advantage'],['global_competitiveness','global'],['methodology','methodology']])if(!f[flag]){$(id).hidden=true;document.querySelector(`nav a[href="#${id}"]`).hidden=true;}
$('menu-button').onclick=()=>{const open=$('nav-links').classList.toggle('open');$('menu-button').setAttribute('aria-expanded',String(open));};document.querySelectorAll('#nav-links a').forEach(a=>a.onclick=()=>{$('nav-links').classList.remove('open');$('menu-button').setAttribute('aria-expanded','false');});
on(['concentration-metric','concentration-level'],()=>guarded('concentration-chart',concentrationChart));on(['eci-ranks'],()=>guarded('eci-chart',eciChart));
if(f.overview)await guarded('kpis',overview);
const lazy={structure:()=>f.export_structure&&guarded('composition-chart',structure),advantage:()=>f.industry_rca&&guarded('industry-chart',industry),global:()=>f.global_competitiveness&&guarded('division-chart',globalDivisions),methodology:()=>f.methodology&&guarded('sources-content',methodology)};
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){const name=e.target.dataset.lazy;once(name,lazy[name]);observer.unobserve(e.target);}}),{rootMargin:'0px'});document.querySelectorAll('[data-lazy]').forEach(e=>observer.observe(e));
}
start().catch(e=>{console.error(e);$('kpis').innerHTML='<p class="error" role="alert">Dashboard data could not be loaded. Please refresh or use a local HTTP server.</p>';});
