import {loadJSON} from './data.js';
import {escapeHTML as e} from './formatters.js';
const plainCaveats={"C01": "The project uses Revision 2 of SITC, the international trade classification. Manufacturing covers Sections 5–8, excluding non-ferrous metals (Division 68).", "C02": "The World Bank comparison uses SITC Revision 3. The average absolute difference is 1.110445 percentage points; the largest is 2.784854 points in 2022. Both series move in the same direction between the endpoints, but their definitions and data versions differ.", "C03": "WTO totals follow calendar years; PBS headline totals use fiscal years and provide context only. Total-export differences average 3.0640%, with a maximum of 9.7380%. The contribution of each possible cause has not been determined.", "C04": "Constant-price values use a common US industrial producer-price index. Monthly values receive equal weight in the annual average. This is a transparent implementation, not a verified copy of the Atlas’s internal code, and it does not measure physical export volume.", "C05": "Concentration depends partly on how finely products are grouped. From 2000 to 2024, the detailed-product index (SITC4) falls, while the broader-product index (SITC3) rises. Top-5 and top-10 detailed-product shares also fall.", "C06": "RCA results also depend on product grouping. The transition categories of 80 detailed products, accounting for 9.7140% of late-period shares, differ from their parent groups. The gained-RCA share is 11.3374% at one level compared with 3.1034% at the other.", "C07": "A high RCA can occur for a product with little export value. RCA does not by itself measure productivity or explain the causes of specialization.", "C08": "The research definition of a material product requires RCA strictly above 1 and a share of at least 0.5% of manufactured exports: 27 products meet this rule. A 1% share cutoff gives 22 products.", "C09": "Period averages use the annual observations that are available. Incomplete periods are disclosed. Late-period product-share averages sum to 100.004152705%, because they are separate period averages, not shares from one year; they are not rescaled to 100%.", "C13": "The supplied SITC Economic Complexity Index covers the wider export basket, not only manufacturing. Its country coverage and data version also matter when interpreting ranks.", "C14": "The supplied world product totals include USD 18,147 in 2001 that is excluded from sums across the project’s reporting economies. World denominators follow the supplied Growth Lab product totals.", "C16": "An explicit zero remains zero. A missing product observation is not treated as zero trade, and missing combinations are not created."};
const downloadNames={"Product exports":"Exports by detailed product","Rca products":"Revealed comparative advantage by detailed product","Sitc2 composition":"Manufactured export mix by broad product group","Sitc2 world market share":"Global export shares by broad product group","Rca transitions":"Changes in revealed comparative advantage","World market share":"Pakistan’s share of global manufactured exports","Eci":"Economic Complexity Index","Sources":"Research source bibliography"};
const grains={"year × sitc4":"Each year and detailed product","year × sitc2":"Each year and broad product group","sitc4":"Detailed products","year":"Annual series","source_id":"Source reference list"};
export async function methodology(){const [sources,caveats,downloads]=await Promise.all(['data/lookups/public_sources.json','data/lookups/public_caveats.json','data/download_manifest.json'].map(loadJSON));
document.getElementById('sources-content').innerHTML='<ul>'+sources.map(s=>`<li><a href="${e(s.source_url)}" target="_blank" rel="noopener noreferrer">${e(s.source_name)}</a><br>${e(s.dataset_name)} · ${e(s.classification||'')}</li>`).join('')+'</ul>';
document.getElementById('methodology-content').innerHTML='<p>Manufacturing covers product groups 5–8 in Revision 2 of SITC, the international trade classification, except non-ferrous metals (Division 68). The figures shown come from the validated research tables. Constant 2024 US dollars adjust for broad price changes, not physical volumes. Revealed comparative advantage (RCA) compares a product’s importance in Pakistan’s goods exports with its importance in world goods exports. The period comparisons use 2000–02 and 2022–24. The Economic Complexity Index covers the wider export basket.</p><p>Technology-classification data are not included in this public release.</p>';
let all=false;const render=()=>{document.getElementById('caveats-content').innerHTML=caveats.slice(0,all?caveats.length:4).map(c=>`<h3>${e(c.topic)}</h3><p>${e(plainCaveats[c.caveat_id]||c.description)}</p>`).join('');document.getElementById('all-caveats').textContent=all?'Show fewer caveats':'Show all caveats';};render();document.getElementById('all-caveats').onclick=()=>{all=!all;render();};
document.getElementById('downloads-content').innerHTML=downloads.map(d=>`<div><a download href="${e(d.file)}">${e(downloadNames[d.display_name]||d.display_name)}</a><span class="small">${e(d.dataset_type)} · ${(d.size_bytes/1000).toFixed(1)} kB · ${e(grains[d.description]||d.description)}</span></div>`).join('');}
